# Generated by Django 5.1.3 on 2026-04-29 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reviewer_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("correct", "Correct"),
                            ("partial", "Partially correct"),
                            ("incorrect", "Incorrect"),
                        ],
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("corrected_response", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="chatbot.chatmessage",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="reports.report",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="chatbot.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["session", "-created_at"],
                        name="chatbot_mes_session_d5bae1_idx",
                    ),
                    models.Index(
                        fields=["verdict"], name="chatbot_mes_verdict_acc01a_idx"
                    ),
                ],
            },
        ),
    ]
