# Generated by Django 5.1.3 on 2026-05-24 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_messagereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPhenotypeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpo_terms', models.JSONField(blank=True, default=list)),
                ('candidate_genes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phenotype_profile', to='chatbot.chatsession')),
            ],
        ),
    ]
