# Generated by Django 5.1.3 on 2026-04-15 07:26

import django.db.models.deletion
import reports.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("wgs", "WGS"),
                            ("wes", "WES"),
                            ("oral", "Oral Microbiome"),
                            ("gut", "Gut Microbiome"),
                            ("skin", "Skin Microbiome"),
                            ("vaginal", "Vaginal Microbiome"),
                        ],
                        max_length=16,
                    ),
                ),
                ("file", models.FileField(upload_to=reports.models.report_upload_path)),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("parsed_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="reports_rep_owner_i_aeee04_idx",
                    ),
                    models.Index(
                        fields=["report_type"], name="reports_rep_report__dbb097_idx"
                    ),
                ],
            },
        ),
    ]
