# Generated by Django 5.1.3 on 2026-05-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='enrichment_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='enrichment_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='enrichment_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='report',
            name='enrichment_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
