# Generated by Django 5.1.3 on 2026-05-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_enrichment_data_report_enrichment_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('wgs', 'WGS'), ('wes', 'WES'), ('oral', 'Oral Microbiome'), ('gut', 'Gut Microbiome'), ('skin', 'Skin Microbiome'), ('vaginal', 'Vaginal Microbiome'), ('clinical_csv', 'Clinical Variant CSV')], max_length=16),
        ),
    ]
