# Generated by Django 5.1.3 on 2026-05-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('wgs', 'WGS'), ('wes', 'WES'), ('oral', 'Oral Microbiome'), ('gut', 'Gut Microbiome'), ('skin', 'Skin Microbiome'), ('vaginal', 'Vaginal Microbiome'), ('clinical_csv', 'Clinical Variant CSV'), ('intervar', 'InterVar TXT')], max_length=16),
        ),
    ]
