# Generated by Django 5.1.3 on 2026-05-14 12:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FranklinCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('gene', 'Gene'), ('variant', 'Variant')], max_length=16)),
                ('cache_key', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=8)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('-fetched_at',),
                'indexes': [models.Index(fields=['kind', 'cache_key', 'reference'], name='franklin_fr_kind_2469d4_idx'), models.Index(fields=['expires_at'], name='franklin_fr_expires_46067f_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'cache_key', 'reference'), name='franklin_cache_unique_key')],
            },
        ),
    ]
